### ISSUE TITLE
K-Meter (Stereo x64).exe not starting Win8.1

### ISSUE THREAD

**Issue by Roduleg** [mzuther/K-Meter#10]
I cannot get K-Meter (Stereo x64).exe to run in Win8.1 64bit
I have changed my sound card driver recently 
K-Meter (Surround x64).exe will start!
windows events as follows
.....
Application error 
......
Log Name:      Application
Source:        Application Error
Date:          16/03/2015 3:43:52 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      rodsLT
Description:
Faulting application name: K-Meter (Stereo x64).exe, version: 0.0.0.0, time stamp: 0x51a661c4
Faulting module name: K-Meter (Stereo x64).exe, version: 0.0.0.0, time stamp: 0x51a661c4
Exception code: 0xc0000005
Fault offset: 0x0000000000001f4a
Faulting process id: 0x105e4
Faulting application start time: 0x01d05fa3cd6b3275
Faulting application path: C:\Users\rsammut\Desktop\K\kmeter-standalone_1.31\kmeter-standalone_1.31\K-Meter (Stereo x64).exe
Faulting module path: C:\Users\rsammut\Desktop\K\kmeter-standalone_1.31\kmeter-standalone_1.31\K-Meter (Stereo x64).exe
Report Id: 0b284c0d-cb97-11e4-8290-303a648dfc6f
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-03-16T04:43:52.000000000Z" />
    <EventRecordID>29315</EventRecordID>
    <Channel>Application</Channel>
    <Computer>rodsLT</Computer>
    <Security />
  </System>
  <EventData>
    <Data>K-Meter (Stereo x64).exe</Data>
    <Data>0.0.0.0</Data>
    <Data>51a661c4</Data>
    <Data>K-Meter (Stereo x64).exe</Data>
    <Data>0.0.0.0</Data>
    <Data>51a661c4</Data>
    <Data>c0000005</Data>
    <Data>0000000000001f4a</Data>
    <Data>105e4</Data>
    <Data>01d05fa3cd6b3275</Data>
    <Data>C:\Users\rsammut\Desktop\K\kmeter-standalone_1.31\kmeter-standalone_1.31\K-Meter (Stereo x64).exe</Data>
    <Data>C:\Users\rsammut\Desktop\K\kmeter-standalone_1.31\kmeter-standalone_1.31\K-Meter (Stereo x64).exe</Data>
    <Data>0b284c0d-cb97-11e4-8290-303a648dfc6f</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

.........
Windows error reporting
.....
Log Name:      Application
Source:        Windows Error Reporting
Date:          16/03/2015 3:43:53 PM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      rodsLT
Description:
Fault bucket 112882388, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: K-Meter (Stereo x64).exe
P2: 0.0.0.0
P3: 51a661c4
P4: K-Meter (Stereo x64).exe
P5: 0.0.0.0
P6: 51a661c4
P7: c0000005
P8: 0000000000001f4a
P9: 
P10: 

Attached files:
C:\Users\rsammut\AppData\Local\Temp\WERDB01.tmp.WERInternalMetadata.xml
C:\Users\rsammut\AppData\Local\Temp\WERDF28.tmp.appcompat.txt
C:\Users\rsammut\AppData\Local\Temp\WERDF29.tmp.dmp
C:\Users\rsammut\AppData\Local\Temp\WERDF79.tmp.WERDataCollectionFailure.txt

These files may be available here:
C:\Users\rsammut\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_K-Meter (Stereo _50eec9b75fbe54aa8558b4f1e3540b3dcd0d1f8_a88e5193_0605df76

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0b284c0d-cb97-11e4-8290-303a648dfc6f
Report Status: 4104
Hashed bucket: f0e24aafec7833ca579d2b73e4a9d8b6
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-03-16T04:43:53.000000000Z" />
    <EventRecordID>29316</EventRecordID>
    <Channel>Application</Channel>
    <Computer>rodsLT</Computer>
    <Security />
  </System>
  <EventData>
    <Data>112882388</Data>
    <Data>4</Data>
    <Data>APPCRASH</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>K-Meter (Stereo x64).exe</Data>
    <Data>0.0.0.0</Data>
    <Data>51a661c4</Data>
    <Data>K-Meter (Stereo x64).exe</Data>
    <Data>0.0.0.0</Data>
    <Data>51a661c4</Data>
    <Data>c0000005</Data>
    <Data>0000000000001f4a</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
C:\Users\rsammut\AppData\Local\Temp\WERDB01.tmp.WERInternalMetadata.xml
C:\Users\rsammut\AppData\Local\Temp\WERDF28.tmp.appcompat.txt
C:\Users\rsammut\AppData\Local\Temp\WERDF29.tmp.dmp
C:\Users\rsammut\AppData\Local\Temp\WERDF79.tmp.WERDataCollectionFailure.txt</Data>
    <Data>C:\Users\rsammut\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_K-Meter (Stereo _50eec9b75fbe54aa8558b4f1e3540b3dcd0d1f8_a88e5193_0605df76</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>0b284c0d-cb97-11e4-8290-303a648dfc6f</Data>
    <Data>4104</Data>
    <Data>f0e24aafec7833ca579d2b73e4a9d8b6</Data>
  </EventData>
</Event>

**Comment by mzuther** [comment]
Sorry to hear that. However, the stand-alone (EXE file) is mostly for debugging and running on Linux. Have you tried to use the VST plug-in? Maybe you can route your sound card's audio input to K-Meter in your VST host...

**Comment by Roduleg** [comment]
Hi Martin,

 

I only use the meter for monitoring ITunes playback or EAC software  loudness so the VST won’t work.

I have found that the K-Meter (Surround).exe will work with win8.1 so have been using that.

Thanks

Rodney

**Comment by mzuther** [comment]
You could try to delete the file `%UserProfile%\AppData\.config\kmeter_stereo.ini` (something like `C:\Users\Rodney\AppData\.config\kmeter_stereo.ini`, although I'm not sure about the `AppData` part). Sorry, I still use Windows XP for music.

Deleting this file will "reset" the stereo stand-alone and sometimes helps with problems...

**Comment by Roduleg** [comment]
Hi Martin, 

 

That fixed it! Did not know about those files. I did go looking yesterday but was searching for “Kmeter32”.

 

I compared the  working ini with the non-working one replacing lines in the XML

Its this line causing the problem 

<DEVICESETUP deviceType="ASIO" audioOutputDeviceName="" audioInputDeviceName=""/>

 

Both 32 and 64 bit versions work now thankyou

Path is C:\Users\username\AppData\Roaming\.config\kmeter_stereo.ini

 

Regards

Rodney

**Comment by mzuther** [comment]
Thanks for your help!  I thought I was the only one who occasionally had this problem (which is unfortunately out of my control).  Seems like I should add the solution to the documentation...

Martin
