### ISSUE TITLE
A Sonar project saved with K-meter is dead

### ISSUE THREAD

**Issue by CedricDili** [mzuther/K-Meter#11]
First, thanks for this plugin, which is great.
I love Sonar but the meters are not great and needed K-Meter for K-20 / K-14 / K-12.

I tested K-Meter 64 bit VST Stereo for Windows with Sonar Platinum (= Sonar X4 64).
It works well when using it.

However, a project saved with the plugin can't be opened again, it will crash Sonar and launch FaultReporter.exe. So in effect, if you forget to remove K_Meter before saving the project, you can kiss your project goodbye.

**Comment by mzuther** [comment]
Thanks for the bug report. I'm sorry that K-Meter is causing you trouble.

Unfortunately, my time is currently very limited, so I can't do anything about the problem. I have re-written a lot of code and maybe this has fixed the issue, but I don't even find the time to publish a new version.

**Comment by CedricDili** [comment]
Hi Martin,

 

No problem, thanks for making the plugin.

 

I may look at the code on GitHub but knowing nothing about the VST standard I probably won’t detect anything.

 

I’m not 100 % sure it’s your plugin, because the problem didn’t appear so far with Reaper & FL Studio. I did not use it a lot in these DAWs though . Or they are more hardened against VST bugs.

 

With Sonar Platinum, it seems it expects a parameter that isn’t passed and crashes. I’ve opened a ticket with Cakewalk technical support maybe they’ll have something to say.

 

Best regards,

Cédric

 

 

 

 

De : Martin Zuther [mailto:notifications@github.com] 
Envoyé : mercredi 27 mai 2015 21:06
À : mzuther/K-Meter
Cc : CedricDili
Objet : Re: [K-Meter] A Sonar project saved with K-meter is dead (#11)

 

Thanks for the bug report. I'm sorry that K-Meter is causing you trouble.

Unfortunately, my time is currently very limited, so I can't do anything about the problem. I have re-written a lot of code and maybe this has fixed the issue, but I don't even find the time to publish a new version.

**Comment by mzuther** [comment]
Hi Cedric,

I have just released a new version of K-Meter with a lot of internal changes.  Maybe you want to try whether it changes things for good?

Best regards,

Martin
