### ISSUE TITLE
K-Meter 2.6 Not Recognized by Windows XP

### ISSUE THREAD

**Issue by E-Gwen** [mzuther/K-Meter#13]
Hi,

I just tried K-Meter 2.6 but, as a VST Plugin, neither Audacity 2.1.2 neither Ardour 5.3 won't let appear K-Meter as a plugin !

When you install the 2.6 stand-alone pakage, Windows XP doesn't launch it : it says : 
"K-Meter is not a win32 valid application", so you can't run it.

Such a pity.

Best regards.

E-Gwen.

**Comment by mzuther** [comment]
Hi E-Gwen,

thanks for your report! K-Meter does no longer support Windows XP. This is not my fault, the underlying library uses functions that need Windows 7. I have updated my website to reflect this information and added a download to version 2.2.0 which runs on XP.

Best regards,

Martin
