### ISSUE TITLE
LADSPA plug-in? 

### ISSUE THREAD

**Issue by landroni** [mzuther/K-Meter#14]
I would like to use K-Meter in [Audacious](http://audacious-media-player.org/) but unfortunately it only supports [LADSPA](http://www.ladspa.org/) (and not VST). 

Is there any chance that there'll be a LADSPA version of K-Meter in the future?

**Comment by mzuther** [comment]
No, I'm sorry.  There are so many plug-in formats, and my limited time only allows me to concentrate on the most popular / best ones.

If you know a C++ programmer, the port itself should be relatively simple: https://www.juce.com/doc/classLADSPAPluginFormat  To my best knowledge, however, LADSPA doesn't support a custom GUI, so it doesn't make a lot of sense to port K-Meter.

There are two ways out.  The first would be to ask the people at Audacious whether they'll add LV2 support to the player.  After all, LV2 is something like LADSPA v2.

The easy way, however, would be to use Audacious with JACK and simply plug its output into the input of K-Meter stand-alone.  I often do this when I code K-Meter and it works fabulously.  And the best thing is, once you know your way around JACK, you can easily use another player with K-Meter, as long as it supports JACK.

Best,

Martin

**Comment by landroni** [comment]
Thanks a lot for the pointers! I'll try to ask Audacious devels for LV2 support, we'll see how it goes. 

As for JACK, I'll be honest that for years I've been checking its webpage from time to time, and I still haven't figured out how it's supposed to be used...

**Comment by mzuther** [comment]
JACK is some sort of low-latency cable for connecting audio applications.  I use QJackCtl as patchbay that automatically connects my audio applications to the sound card (or each other).

Setting up JACK can (but doesn't have to be) a little complex, but I wouldn't want to live without it.  When I code, I use it to automatically connect K-Meter to any audio source (PulseAudio, Audacity, you get the idea).  It's super convenient and well worth trying out.  Here's something to get you started:
* http://www.rncbc.org/drupal/node/76
* https://www.linuxjournal.com/article/8354?page=0,2

Good luck! :)
