### ISSUE TITLE
ASIO Channel disabling

### ISSUE THREAD

**Issue by kuehn-sba** [mzuther/K-Meter#16]
Is it possible to disable channels in ASIO? I can only change the checkboxes for my asio channels (for example, I can choose between Ch 1-2 or Ch 3-4), but it can not be disabled the specific channel itself.
_(...In the case I want only get input and no output)._

PS: all in all K-Meter is very cute and useful. Thanks a lot.

_Edit: I am able to disable inputs via kmeter_stereo.ini now_

**Comment by mzuther** [comment]
I honestly don't know. The thing is that the behaviour of the stand-alone meter is coded in JUCE, not by me. It works for me, but don't ask me how I got there... :)

(Thanks for the praise!)
