### ISSUE TITLE
Expanded Meters

### ISSUE THREAD

**Issue by kuehn-sba** [mzuther/K-Meter#17]
Can you please tell me, what it is with the marked: 'expanded' skin files on it? Is there any finer representation in 'discrete' mode?

Greetings.

**Comment by mzuther** [comment]
Hi!

I don't know whether I understood your question. Are you trying to create a new skin?  Anyway, in "discrete" mode, the representation is fixed to 0.1 dB per segment (although you can enlarge the segments).  In "continuous" mode, though, the representation only depends on the number of available pixels.

I'll close this issue now, feel free to re-open if you need to.

Greetings,

Martin
