### ISSUE TITLE
Stand-alone crashes / Plug-in does not show in DAW

### ISSUE THREAD

**Issue by mzuther** [mzuther/K-Meter#21]
This is a collection issue that hopefully helps to fix the problem that K-Meter crashes on some Windows installations while it runs just fine on many others.

You are very welcome to help me iron this out. But let me make one thing crystal clear:

**I run my own shop and my spare time is limited. K-Meter is a fun project, and I can only dedicate so much time to it. Please only join if you are dedicated to find and fix this issue which will mean quite a bit of work and research on your own! You'll also need patience.**

On the other hand, I am very grateful if you help me iron this out!

I do not have access to a Windows system that exhibits the problem, otherwise it would have been fixed ages ago. To the contrary: I have tested K-Meter on six systems, from Windows 7 to 10, 32 and 64 bits, one even being vanilla (i.e. a fresh Windows 10 installation with absolutely nothing installed), and the K-Meter stand-alone ran fine on all of them.

Finally, I've got no experience in remote debugging. But I'm willing to learn... :)

**Comment by mzuther** [comment]
Here are the first steps:

1. Please make sure that you are using the correct version, i.e. 32-bit plug-in with 32-bit DAW or 64-bit plug-in with 64-bit DAW. Please check whether the K-Meter stand-alone works.

2. Did you copy the folder "kmeter" to your VST / stand-alone folder?

3. Please check whether [traKmeter](http://code.mzuther.de/trakmeter/) runs on your current system (both as plug-in and stand-alone). It is very similar to K-Meter, but does not depend on the FFTW DLL and needs less resources as well.

Then, report what does and does not work. Please include your exact system and DAW (Windows 7 SP3 64-bit, Reaper 5.70 32- and 64-bit).

Thanks!

Martin

**Comment by 38github** [comment]
Hi Martin,
K-Meter 2.61 x64 does not work in Reaper 5.62 x64 under Windows 10. The x86 version does show up though and Trakmeter 2.00 x64 works.

**Comment by mzuther** [comment]
I have just released K-Meter 2.8.0. Could you please try it and report back?

Thanks,

Martin

**Comment by 38github** [comment]
I have tried the vst3 in Reaper on my laptop and it works. I will try it out on the desktop computer asap. I also tried the Linux VST and LV2 and they worked in Arch and Reaper. Thank you as always through the years for the help!

**Comment by mzuther** [comment]
Thanks for the feed-back. And you're more than welcome! :)

**Comment by mzuther** [comment]
Fixed in v2.8.0. Closing...
