### ISSUE TITLE
Performance issues while the plugin is processing silence

### ISSUE THREAD

**Issue by sagamusix** [mzuther/K-Meter#22]
A user of my plugin host, [OpenMPT](https://openmpt.org/) has reported performance issues with this plugin. It seems like it will make sound output stutter and produce a high CPU load whenever its input is total silence. To me that sounds like [denormals](https://en.wikipedia.org/wiki/Denormal_number) are generated somewhere in the audio processing path. Observed with both 32-bit and 64-bit Windows VST2 builds.

**Comment by sagamusix** [comment]
Okay, I did a very quick modification to OpenMPT to instruct the CPU to flush all denormals to zero before calling the plugin's process function. It causes the plugin to behave well again, so there are definitely some denormals being processed. Some hosts may always be enforcing flushing denormals to zero so the problem does not manifest in them, but I don't think that the host should do that. If the plugin relies on flushing denormals to zero, it should do the necessary CPU state modifications, or it should avoid generating denormals altogether.

**Comment by mzuther** [comment]
Hi!

I've got very little time these days and possibly will for the coming months. That being said, I have devised a work-around (one single line, you wouldn't believe it) and committed it to a branch called "use_denormals". Feel free to test this -- if it solves the problem, I will release an updated version.

Thanks!

Martin

**Comment by sagamusix** [comment]
Hi Martin, the use_denormals branch does indeed fix the issue. Thanks for the quick reply!

**Comment by mzuther** [comment]
That's great to hear! Could you please check the use_denormals branch once again? I have dropped all manual denormalization and would like to know whether that is prudent. :)

Thanks,

Martin

**Comment by sagamusix** [comment]
Still seems to work as intended with the latest changes.

**Comment by mzuther** [comment]
Thanks! I have just released a new version with the use_denormals fix.

Martin
