### ISSUE TITLE
Several improvements

### ISSUE THREAD

**Issue by romanlevchuk777** [mzuther/K-Meter#23]
Hi, 

I'm using your K-meter application for almost 1 year and pretty like it!

Since your app is a first of all - measurement tool - it would be good to implement the next things:

1 - Show momentary value of RMS level in numberic format with refreshing, for example, every 0.5s or 0.25s as it already done for peaks.
2 - Add the ability to change the time of RMS metering and add ability to change the release time of the RMS meter and make it more fast or slow.
3 - Add the ability to callibrate the meter using coeficients.
For examle:
We have -10 dB of input signal. By specifying in seperate text field positive or negative value - we can change overall indicated level, e.q. in case if we set this value equal to -1.8 for Left and -1.6 for Right - the meter will show -10-1.8=11.8 dB for Left channel and -10-1.6=-11.6 for right channel. This will make an ability to calibrate the meter to some reference level more flexible and per channel.

Hope that, my explanation - is clear.

Thanks for the exellent product!

Good luck!

**Comment by mzuther** [comment]
Hi,

thanks for the praise and your ideas! :)

1.  Showing the momentary RMS level is a nice idea. I'll have to think about it, however, as it might clutter up the layout and distract from the important read-outs. I'm currently reading a book on good UI design and still have to digest it. ;)

1.  The timings are given in the K-System meter specifications, so I cannot change them.

    What RMS integration time(s) you would like to see?

    _Note to self: in the current implementation, the RMS integration time is specified in samples and thus changes according to sample rate. That could be considered a bug._

1.  Unfortunately, I cannot add calibration of the meter using coefficients. This would be confusing to anyone but you. K-Meter is used by quite a few professionals who rely on it to be simple to use and reliable.

    But there's an easy solution: simply add a gain plug-in in front of the meter (say +0.2 dB) and another one after the meter, set to the exact opposite (in this case, -0.2 dB). That would be the equivalent of calibrating the meter to -11.8 dBFS.

Best regards,

Martin

**Comment by mzuther** [comment]
Hi,

after thinking a lot about your proposals, I have decided against implementing them. While K-Meter *is* a (high-)precision instrument, it is *not* meant as a numeric measurement tool.

Too many people mix by numbers and I do not want to encourage this by providing more than what is strictly necessary. More importantly, professional users have limited time at their disposal and need tools which allow them to focus on what's important. K-Meter already has way too many buttons...

Still, I want to thank you for letting me view K-Meter from a different angle. This was very helpful!

Martin
