### ISSUE TITLE
Updating JACK client name...

### ISSUE THREAD

**Issue by pabloaugusta** [mzuther/K-Meter#25]
Thanks for K-Meter. I'm using it in conjunction with Blender when video editing.

I'm wondering if/when you build another version of K-Meter you could update the JACK client name from "JUCEJack" to "K-Meter". This would help when connecting standalone applications inside of JACK Audio Connection Kit. Some other apps have forgotten to change the JACK client name and are labelled "JUCEJack".

Thank you in advance.

**Comment by mzuther** [comment]
Done, I just had to add a single line of code. :)  Thanks!

I'll leave this open to remind me of releasing an update in the future...

**Comment by mzuther** [comment]
Just released the update. Enjoy! :smile:
