### ISSUE TITLE
Level bar Bug 

### ISSUE THREAD

**Issue by DAZZER7** [mzuther/K-Meter#27]
### Describe the bug

The standalone K-Meter level bar doesn't work properly.

### Steps to reproduce

1. Start playing music (player or whatever)
2. Start K-Meter
3. The K-Meter level bars rise up and down all the time (by fits and starts)

### Expected behavior

The K-Meter level bars shouldn't display by fits and starts all the time during music play.

### Screenshots

gif file with an issue attached

### Environment (please complete the following information)

 - OS: Windows 10 (64-bit)
 - K-Meter v2.8.1 stand-alone (64-bit) 

Did you compile K-Meter yourself? [no]

### Additional context

![K-Meter issue](https://user-images.githubusercontent.com/70716104/92147762-398d0d00-ee24-11ea-8e55-b1cb2f78457f.gif)

**Comment by mzuther** [comment]
Thanks for the bug report! I can't do much about it as the whole stand-alone code comes from a library.

Still, let's have a try! Could you please tell me your current audio settings (click on _Options -> Audio/MIDI Settings_ on the top of Squeezer's window)? If you can find out, it would also be nice to know for certain whether sample rate and buffer size of Squeezer match your sound card's settings.

**Comment by DAZZER7** [comment]
It's doesn't matter which driver (Windows Audio or Direct Sound) I choose and the size of the buffer. This behavior is still the same, but If I open a second K-Meter the problem fixes on both copies. Also If I start another analyzer/meter (Pinguin, Youlean etc) first, which works correctly and then start K-Meter, it works normally.

**Comment by mzuther** [comment]
Nothing I can do here, I fear.
