### ISSUE TITLE
Bug: HiDPi not scaling

### ISSUE THREAD

**Issue by WMRamadan** [mzuther/K-Meter#28]
### Describe the bug

K-Meter is not scaling with HiDPi enabled.

### Steps to reproduce

1. Start kmeter with either Standalone or vst2 with HiDPi

### Expected behavior

Should scale interface appropriately to screen DPI settings.

### Screenshots

![Screenshot from 2021-06-12 18-01-52](https://user-images.githubusercontent.com/1612303/121780295-5b33d580-cba8-11eb-81d5-34ac634f8738.png)

### Environment (please complete the following information)

 - OS: Linux Kernel 5.11.0-7614-generic, Pop! OS 20.10, GNOME 3.38.3, X11
 - DAW: Carla2 64bit
 - Plug-in: kmeter-linux64-vst2_2.8.2

Did you compile K-Meter yourself? NO

**Comment by mzuther** [comment]
Thanks for your bug report!

I'm aware of the issue and have started to implement GUI scaling. The code is almost complete, but I haven't yet found the time to change the skin files.

I will probably do so in the future, but there are other more urgent issues - and I'm starting a new job next month. :smile: So I fear that it won't be anytime soon...

**Comment by xhub** [comment]
Any update on the GUI scaling? That would be so great! Happy to test if that helps.

**Comment by mzuther** [comment]
I am sorry, but I have to close this issue because I simply do not have enough time to support this project.
